name: Build Single Image
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@master

    - run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install libelf-dev

    - name: Build Image
      run: |
        bash build.sh

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: image
        path: out/images